### ISSUE TITLE
Glitched rendering table of PDF by exported in v0.0.9

### ISSUE THREAD

**Issue by yhatt** [yhatt/marp#101]
In v0.0.9, rendering table in exported PDF have a glitch.
This glitch is not occured in preview pane. It only has in PDF.

[example-exported-in-v0.0.9.pdf](https://github.com/yhatt/marp/files/517925/example-exported-in-v0.0.9.pdf)
#### Glitched page

Duplicated table header :arrow_down:

![glitched_page](https://cloud.githubusercontent.com/assets/3993388/19215818/5c60e072-8de3-11e6-906b-4591cb8bcd8c.png)

**Comment by yhatt** [comment]
I made markdown for testing this issue:

```md
# First page

---

|Table 1|
|:---:|
|Test table|

|Table 2|
|:---|
|Test table|

|Table 3|
|---:|
|Test table|
```

The table header duplication will occur in after second page.

**Comment by yhatt** [comment]
Reported Chromium bug tracker, and already fixed in Chromium 54: https://bugs.chromium.org/p/chromium/issues/detail?id=631222

We should wait update of Electron, included Chromium 54 (perhaps Electron 1.5.x).

**Comment by wangruohui** [comment]
Does it mean that this problem can not be solved at this stage before Electron is updated?

**Comment by yhatt** [comment]
Yes, Marp cannot affect Electron's PDF rendering.

Luckily [Electron 1.3.8](https://github.com/electron/electron/releases) (Chromium 52 and it have not a glitch) had updated as the latest release. Marp is not using 1.4.x new features currently.

Perhaps the current best way to fix may update [Electron to 1.3.8](https://github.com/yhatt/marp/blob/fix-building-electron-version/package.json#L20).

**Comment by wangruohui** [comment]
Thanks for your reply. But I am still a little bit confusing about the Electron. Should I install it stand alone or it is already included in the release of marp? Does marp require external software (such as Electron or others) to render the PDF? As I didn't have either Chromium or Electron installed on my computer, but I can still get the PDF generated.

**Comment by yhatt** [comment]
Electron has already included in the release of Marp. You don't have to install external software (unless you are Marp developer).

**Comment by yhatt** [comment]
Temporarily we rollbacked to Electron. We will update when Electron 1.5.x is released
